### PR TITLE
Call setTimer() again even after action() error.

### LINKED ISSUE #10: Invalid state when action throws exception
If my action throw an exception, the $.timer object does not set the next execution and has `timer.isActive=true`.

This is pretty obvious on your code here: https://github.com/jchavannes/jquery-timer/blob/b43a3cebf890ad56c22975c1bf3b354fbde432b9/jquery.timer.js#L99

If `this.action()` fails for some reason, you don't set the timer again.

### PR DESCRIPTION
**Pull request by iurisilvio**
Fix #10.

### CODE REVIEW

**Comment by iulianmids** [comment]
hello, I have 2 or more animations on page that trigger on hover and if one is in progress and I hover on another, the first one (in progress) stops. any ideeas why? Thanks

**Comment by iurisilvio** [comment]
@iulianmids I think it is not related to this issue, but you're probably using the same timer to both elements and losing the reference for the first animation.

**Comment by iulianmids** [comment]
I tried to make 2 different variables that instantiate $.timer() but it still stops..
i have something like:
var random = 'emoti'+Math.floor((Math.random() * 1000) + 1);
var random = $.timer(function(){ ...code....}});
random.set({ time : 80, autostart : false });
random.play(true);
and all this is parsed on hover

**Comment by iurisilvio** [comment]
I don't know what you are doing in your timer, the problem is probably
there.

**Comment by iulianmids** [comment]
I want to do something like facebook emoticons
emoti
and on hover animate them.

So basically this should work. The problems is in my code somewhere.
I was asking because I tought that maybe it doesn't suppose to work :)

**Pull request merged**
